[build]
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION='10.16.0'
  YARN_FLAGS='--pure-lockfile'
  REACT_APP_DFAIRDEX_URL='https://dfairdex.netlify.com/'
  REACT_APP_NINJATRADE_URL='https://ninja-trade.netlify.com/'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
